### ISSUE TITLE
Non-leader unit stuck on `unknown/idle`

### ISSUE THREAD

**Issue by sed-i** [canonical/tls-certificates-requirer-operator#22]
After deploying two units of this app,
```yaml
bundle: kubernetes
applications:
  ca:
    charm: self-signed-certificates
    channel: edge
    revision: 42
    scale: 1
    constraints: arch=amd64
  req:
    charm: tls-certificates-requirer
    channel: edge
    revision: 13
    scale: 2
    constraints: arch=amd64
relations:
- - req:certificates
  - ca:certificates
```

the status of the non-leader is stuck on `unknown/idle`.

```
Model  Controller  Cloud/Region        Version  SLA          Timestamp
pt     k8s2        microk8s/localhost  3.1.6    unsupported  22:02:53-04:00

App  Version  Status   Scale  Charm                      Channel  Rev  Address         Exposed  Message
ca            active       1  self-signed-certificates   edge      42  10.152.183.105  no       
req           waiting      2  tls-certificates-requirer  edge      13  10.152.183.217  no       installing agent

Unit    Workload  Agent  Address       Ports  Message
ca/0*   active    idle   10.1.166.77          
req/0*  active    idle   10.1.166.116         
req/1   unknown   idle   10.1.166.113         

Integration provider  Requirer          Interface         Type     Message
ca:certificates       req:certificates  tls-certificates  regular  
```

Scaling to 4 is the same
```
Unit    Workload  Agent  Address       Ports  Message
ca/0*   active    idle   10.1.166.77        
req/0*  active    idle   10.1.166.116       
req/1   unknown   idle   10.1.166.113       
req/2   unknown   idle   10.1.166.100         
req/3   unknown   idle   10.1.166.102
```

I expected to see a cert per unit. I guess that is not the case because certs are communicated over app data rather than unit data?
